name: Backup Script CI

on:
    push:

jobs:
    test-backup:
        runs-on: ubuntu-latest
        
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Setup Python
              uses: actions/setup-python@v4
              with:
                python-version: "3.12"

            - name: Install Dependencies
              run: pip install boto3    

            - name: Configure AWS Credentials
              uses : aws-actions/configure-aws-credentials@v4
              with:
                aws-access-key-id : ${{secrets.AWS_ACCESS_KEY}}  
                aws-secret-acess-key: ${{secrets.AWS_SECRET_KEY}}
                aws-region: ap-south-1
              
              
              
            - name: Upload Backup to AWS S3
              run: python s3_backup.py
              
